# Generated by Django 5.0.1 on 2026-02-20 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_type', models.CharField(choices=[('none', 'No Subscription'), ('mark', "Mark's Agent"), ('hr', 'HR Agent'), ('both', 'Both Agents')], default='none', max_length=10)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, help_text='Null = no expiry', null=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('monthly_quota', models.IntegerField(default=1000)),
                ('current_month_usage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['subscription_status'], name='tenants_subscri_f58e68_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('mark', 'Mark'), ('hr', 'HR')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('unauthorized', 'Unauthorized'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='auth_app.userprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent_request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='agent_reque_tenant__22547d_idx'), models.Index(fields=['user', '-created_at'], name='agent_reque_user_id_307097_idx'), models.Index(fields=['agent_type', '-created_at'], name='agent_reque_agent_t_759dca_idx'), models.Index(fields=['status'], name='agent_reque_status_7b1b9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('mark', "Mark's Agent"), ('hr', 'HR Agent')], max_length=10)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retries', models.IntegerField(default=3)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent_configs',
                'ordering': ['tenant', 'agent_type'],
                'unique_together': {('tenant', 'agent_type')},
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="E.g. 'Production Website'", max_length=100)),
                ('key_hash', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(help_text='First 10 chars for identification', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_prefix'], name='tenant_api__key_pre_65c034_idx'), models.Index(fields=['tenant', 'is_active'], name='tenant_api__tenant__14c4b8_idx')],
            },
        ),
    ]
