# Generated by Django 5.0.1 on 2026-02-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Company/org this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['supabase_uid'], name='user_profil_supabas_02edd6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='user_profil_email_8a1024_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant'], name='user_profil_tenant__474e22_idx'),
        ),
    ]
