# Generated by Django 6.0.2 on 2026-02-17 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_email_e3bad1_idx',
            old_name='loginattem_email_5a5f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_ip_addr_d06a3f_idx',
            old_name='loginattem_ip_addr_8f6c12_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_success_e73d81_idx',
            old_name='loginattem_success_9a7b23_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_supabas_a91415_idx',
            old_name='supabase_us_supabas_6f0c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_email_8d2eac_idx',
            old_name='supabase_us_email_6f5f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_tenant__6e600f_idx',
            old_name='supabase_us_tenant__4d5e10_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_is_acti_04954d_idx',
            old_name='supabase_us_is_acti_7e6a12_idx',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supabaseuser',
            name='can_access_hr',
            field=models.BooleanField(default=False, help_text='Can access HR Agent'),
        ),
        migrations.AlterField(
            model_name='supabaseuser',
            name='can_access_mark',
            field=models.BooleanField(default=False, help_text="Can access Mark's Agent"),
        ),
        migrations.AlterField(
            model_name='supabaseuser',
            name='email',
            field=models.EmailField(help_text="User's email from Supabase", max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
